src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CustomerRepository::class)]
class Customer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $lastname;

    #[ORM\Column(type: 'string', length: 255)]
    private $firstname;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $adresse;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ville;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $code_postal;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $telephone;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $portable;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $fax;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $mail;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $website;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $raison_sociale;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $forme_juridique;

    #[ORM\OneToMany(mappedBy: 'id_customer', targetEntity: Facture::class)]
    private $factures;

    #[ORM\OneToMany(mappedBy: 'id_customer', targetEntity: Devis::class)]
    private $devis;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'customers')]
    #[ORM\JoinColumn(nullable: true)]
    private $user;

    public function __construct()
    {
        $this->factures = new ArrayCollection();
        $this->devis = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(?int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getPortable(): ?string
    {
        return $this->portable;
    }

    public function setPortable(?string $portable): self
    {
        $this->portable = $portable;

        return $this;
    }

    public function getFax(): ?string
    {
        return $this->fax;
    }

    public function setFax(?string $fax): self
    {
        $this->fax = $fax;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(?string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raison_sociale;
    }

    public function setRaisonSociale(?string $raison_sociale): self
    {
        $this->raison_sociale = $raison_sociale;

        return $this;
    }

    public function getFormeJuridique(): ?string
    {
        return $this->forme_juridique;
    }

    public function setFormeJuridique(?string $forme_juridique): self
    {
        $this->forme_juridique = $forme_juridique;

        return $this;
    }

    /**
     * @return Collection<int, Facture>
     */
    public function getFactures(): Collection
    {
        return $this->factures;
    }

    public function addFacture(Facture $facture): self
    {
        if (!$this->factures->contains($facture)) {
            $this->factures[] = $facture;
            $facture->setIdCustomer($this);
        }

        return $this;
    }

    public function removeFacture(Facture $facture): self
    {
        if ($this->factures->removeElement($facture)) {
            // set the owning side to null (unless already changed)
            if ($facture->getIdCustomer() === $this) {
                $facture->setIdCustomer(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Devis>
     */
    public function getDevis(): Collection
    {
        return $this->devis;
    }

    public function addDevi(Devis $devi): self
    {
        if (!$this->devis->contains($devi)) {
            $this->devis[] = $devi;
            $devi->setIdCustomer($this);
        }

        return $this;
    }

    public function removeDevi(Devis $devi): self
    {
        if ($this->devis->removeElement($devi)) {
            // set the owning side to null (unless already changed)
            if ($devi->getIdCustomer() === $this) {
                $devi->setIdCustomer(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/CustomerType.php
<?php

namespace App\Form;

use App\Entity\Customer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\ChoiceList\ChoiceList;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;

class CustomerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options ): void
    {
        $builder
            ->add('lastname', TextType::class, [
                'label' => 'Nom' ,
                'attr' => [
                    'class' =>'form-control',
                    'required' => false
                ]
            ])
            ->add('firstname', TextType::class, [
                'label' => 'Prénom' ,
                'attr' => [
                    'class' =>'form-control',
                    'required' => false
                ]
            ])
            ->add('adresse', TextType::class, [
                'label' => 'Adresse' ,
                'attr' => [
                    'class' =>'form-control',
                    'required' => false
                ]
            ])
            ->add('ville', TextType::class, [
                'attr' => [
                    'class' =>'form-control',
                    'required' => false
                ]
            ])
            ->add('code_postal', NumberType::class, [
                'attr' => [
                    'class' =>'form-control',
                    'required' => false
                ]
            ])
            ->add('telephone', TextType::class, [
                'attr' => [
                    'class' =>'form-control',
                    'required' => false
                ]
            ])
            ->add('portable', TextType::class, [
                'attr' => [
                    'class' =>'form-control',
                    'required' => false
                ]
            ])
            ->add('fax', TextType::class, [
                'attr' => [
                    'class' =>'form-control',
                    'required' => false
                ]
            ])
            ->add('mail', TextType::class, [
                'label' => 'Email' ,
                'attr' => [
                    'class' =>'form-control',
                    'required' => false
                ]
            ])
            ->add('website', TextType::class, [
                'label' => 'Site Web' ,
                'attr' => [
                    'class' =>'form-control',
                    'required' => false
                ]
            ])
            ->add('raison_sociale', TextType::class, [
                'label' => 'Raison sociale' ,
                'attr' => [
                    'class' =>'form-control',
                    'required' => false
                ]
            ])
            ->add('forme_juridique', ChoiceType::class, [
                'label' => 'Forme Juridique' ,
                'attr' => [
                    'class' =>'form-control',
                    'required' => false
                ],
                'choices' => [   
                    '...' =>  ChoiceList::attr($this, function (?Customer $customer) {
                        return  $customer->getFormeJuridique();
                    }),                
                    'SARL' => 'SARL',
                    'SAS' => 'SAS',                    
                    'Association' => 'Association',                    
                    'Auto-Entreprise' => 'Auto-Entreprise',                    
                    'Client' => 'Client',                    
                ],
            ])
            //->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Customer::class,
        ]);
    }
}

src/Controller/CustomerController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Customer;
use App\Form\CustomerType;
use App\Repository\CustomerRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/customer')]
class CustomerController extends AbstractController
{
    #[Route('/', name: 'app_customer_index', methods: ['GET'])]
    public function index(CustomerRepository $customerRepository, PaginatorInterface $paginator, Request $request): Response
    {        
        $data = $customerRepository->findBy(['user' => $this->getUser()]);
        $customers = $paginator->paginate(
            $data, // Requête contenant les données à paginer (ici nos articles)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            10 // Nombre de résultats par page
        );
        return $this->render('customer/index.html.twig', [
            'customers' => $customers,


        ]);
    }

    #[Route('/new', name: 'app_customer_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CustomerRepository $customerRepository): Response
    {
        $customer = new Customer();
        $form = $this->createForm(CustomerType::class, $customer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $customerRepository->add($customer);
            return $this->redirectToRoute('app_customer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('customer/new.html.twig', [
            'customer' => $customer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_customer_show', methods: ['GET'])]
    public function show(Customer $customer): Response
    {
        return $this->render('customer/show.html.twig', [
            'customer' => $customer,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_customer_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Customer $customer, CustomerRepository $customerRepository): Response
    {
        $form = $this->createForm(CustomerType::class, $customer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $customerRepository->add($customer);
            return $this->redirectToRoute('app_customer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('customer/edit.html.twig', [
            'customer' => $customer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_customer_delete', methods: ['POST'])]
    public function delete(Request $request, Customer $customer, CustomerRepository $customerRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$customer->getId(), $request->request->get('_token'))) {
            $customerRepository->remove($customer);
        }

        return $this->redirectToRoute('app_customer_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/customer/_delete_form.html.twig
<form method="post" action="{{ path('app_customer_delete', {'id': customer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ customer.id) }}">
    <button class="btn">Supprimer &nbsp;<i class="fa-solid fa-trash-can"></i></button>
</form>

templates/customer/_form.html.twig
<div class="dataContainer">
{{ form_start(form) }}
<div class="row g-3 ">
  <div class="col-md-6">    
    {{ form_row(form.lastname) }}
  </div>
  <div class="col-md-6">    
    {{ form_row(form.firstname) }}
  </div>

  <div class="col-12">
    {{ form_row(form.adresse) }}
  </div>

  <div class="col-md-6">
    {{ form_row(form.ville) }}
  </div>
  <div class="col-md-6">
    {{ form_row(form.code_postal) }}
  </div>

  <div class="col-md-4">
    {{ form_row(form.telephone) }}
  </div>
  <div class="col-md-4">
    {{ form_row(form.portable) }}
  </div>
  <div class="col-md-4">
    {{ form_row(form.fax) }}
  </div>

  <div class="col-md-6">
    {{ form_row(form.mail) }}
  </div>
  <div class="col-md-6">
    {{ form_row(form.website) }}
  </div>

  <div class="col-md-6">
    {{ form_row(form.raison_sociale) }}
  </div>
  <div class="col-md-6">
    <div class="form-check">
        {{ form_row(form.forme_juridique) }}
    </div>
  </div>

  <div class="col-12">
    <button type="submit" class="btn btn-primary">{{ button_label|default('Ajouter') }}</button>
  </div>

</div>
{{ form_end(form) }} 
</div>

templates/customer/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Customer{% endblock %}

{% block body %}
<hr>
<table class="titleTab">
  <tr>
    <td class='left'>
        <h1 class="userTitle"><i class="fa-solid fa-users"></i> &nbsp;&nbsp; Modifier  le client</h1>
    </td>
    <td class='right'>   
        <div class="button_slide slide_right">{{ include('customer/_delete_form.html.twig') }}</div>
    </td>
  </tr>
</table> 
<hr>

    {{ include('customer/_form.html.twig', {'button_label': 'Mise à jour'}) }}  
{% endblock %}

templates/customer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Customer index{% endblock %}

{% block body %}
<hr>
<table class="titleTab">
  <tr>
    <td class='left'>
        <h1 class="userTitle"><i class="fa-solid fa-users"></i> &nbsp;&nbsp; Liste des Clients</h1>
    </td>
    <td class='right'>        
        <div class="button_slide slide_right"><a href="{{ path('app_customer_new') }}"><i class="fa-solid fa-plus"></i> &nbsp;Ajouter </a></div>
    </td>
  </tr>
</table>    
<hr>

<div class="dataList">
    <div class="table-responsive">
        <table class="table table-striped table-dark">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Nom</th>
              <th scope="col">Adresse</th>
              <th scope="col">Code Postal</th>
              <th scope="col">Ville</th>
              <th scope="col">Téléphone</th>
              <th scope="col">Portable</th>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
          {% for customer in customers %}
            <tr>
                <td>{{ customer.id }}</td>
                <td>{{ customer.lastname }} {{ customer.firstname }}</td>
                <td>{{ customer.adresse }}</td>
                <td>{{ customer.codePostal }}</td>
                <td>{{ customer.ville }}</td>                
                <td>{{ customer.telephone }}</td>
                <td>{{ customer.portable }}</td>
                <td><a href="{{ path('app_customer_show', {'id': customer.id}) }}"><i class="fa-solid fa-magnifying-glass"></i></a></td>
                <td><a href="{{ path('app_customer_edit', {'id': customer.id}) }}"><i class="fa-solid fa-pen-to-square"></i></a></td>
            </tr>
          {% else %}
            <tr>
                <td colspan="14">aucun résultat</td>
            </tr>
          {% endfor %}      
          </tbody>
        </table>
        <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        {{ knp_pagination_render(customers) }}
        </ul>
        </nav>
    </div>
</div>

{% endblock %}

templates/customer/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Customer{% endblock %}

{% block body %}
<hr>
<table class="titleTab">
  <tr>
    <td class='left'>
        <h1 class="userTitle"><i class="fa-solid fa-users"></i> &nbsp;&nbsp; Nouveau client</h1>
    </td>
    <td class='right'>   
        &nbsp;
    </td>
  </tr>
</table> 
<hr>

    {{ include('customer/_form.html.twig') }}

{% endblock %}

templates/customer/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Customer{% endblock %}

{% block body %}
<hr>
<table class="titleTab">
  <tr>
    <td class='left'>
        <h1 class="userTitle"><i class="fa-solid fa-users"></i> &nbsp;&nbsp; Information client</h1>
    </td>
    <td class='right'>   
        <div class="button_slide slide_right">{{ include('customer/_delete_form.html.twig') }}</div>
    </td>
  </tr>
</table> 
<hr>

<div class="dataContainer py-4">

    <div class="p-3 mb-4 data-bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold"><i class="fa-solid fa-address-card"></i> {{ customer.lastname }} {{ customer.firstname }}  - <a href="{{ path('app_customer_edit', {'id': customer.id}) }}">modifier</a></h1>
        <p class="col-md-8 fs-8">{{ customer.adresse }} <br>
        {{ customer.codePostal }} {{ customer.ville }}</p>
        <hr>
        {# <p class="col-md-8 fs-8">
        </p> #}
        <div class="containerTel">
            <div class="dataTel"><i class="fa-solid fa-phone"></i><br>{{ customer.telephone }}</div>
            <div class="dataTel"><i class="fa-solid fa-mobile-screen-button"></i><br>{{ customer.portable }}</div>
            <div class="dataTel"><i class="fa-solid fa-fax"></i><br>{{ customer.fax }}</div>
        </div> 
        <hr>
        <div class="containerTel">
            <div class="dataMail"><i class="fa-solid fa-envelope"></i><br>{{ customer.mail }}</div>
            <div class="dataMail"><i class="fa-solid fa-house-chimney"></i><br>{{ customer.website }}</div>
        </div>        
      </div>
    </div>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">          
          <h2>{{ customer.raisonSociale }}</h2>
          <p>{{ customer.formeJuridique }}</p>
          <p>
            No. Siren :  XXXXXXX<br>
            No. TVA : XXXXXXX
          </p>
          
        </div>
      </div>

      <div class="col-md-6">
        
          <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d11127.30957135032!2d3.0769151999999997!3d45.79468565!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sfr!2sfr!4v1648136428013!5m2!1sfr!2sfr" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>
      
    </div>

    <footer class="pt-3 mt-4 text-muted border-top">
      ID du client : {{ customer.id }}
    </footer>
</div>

{% endblock %}