src/Entity/Facture.php
<?php

namespace App\Entity;

use App\Repository\FactureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FactureRepository::class)]
class Facture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'datetime')]
    private $date;

    #[ORM\Column(type: 'string', length: 255)]
    private $mode_paiement;

    #[ORM\Column(type: 'string', length: 255)]
    private $code_facture;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'factures')]
    private $id_user;

    #[ORM\ManyToOne(targetEntity: Customer::class, inversedBy: 'factures')]
    private $id_customer;

    #[ORM\OneToMany(mappedBy: 'id_facture', targetEntity: ProductFacture::class)]
    private $productFactures;

    public function __construct()
    {
        $this->productFactures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getModePaiement(): ?string
    {
        return $this->mode_paiement;
    }

    public function setModePaiement(string $mode_paiement): self
    {
        $this->mode_paiement = $mode_paiement;

        return $this;
    }

    public function getCodeFacture(): ?string
    {
        return $this->code_facture;
    }

    public function setCodeFacture(string $code_facture): self
    {
        $this->code_facture = $code_facture;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getIdCustomer(): ?Customer
    {
        return $this->id_customer;
    }

    public function setIdCustomer(?Customer $id_customer): self
    {
        $this->id_customer = $id_customer;

        return $this;
    }

    /**
     * @return Collection<int, ProductFacture>
     */
    public function getProductFactures(): Collection
    {
        return $this->productFactures;
    }

    public function addProductFacture(ProductFacture $productFacture): self
    {
        if (!$this->productFactures->contains($productFacture)) {
            $this->productFactures[] = $productFacture;
            $productFacture->setIdFacture($this);
        }

        return $this;
    }

    public function removeProductFacture(ProductFacture $productFacture): self
    {
        if ($this->productFactures->removeElement($productFacture)) {
            // set the owning side to null (unless already changed)
            if ($productFacture->getIdFacture() === $this) {
                $productFacture->setIdFacture(null);
            }
        }

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\Column(type: 'float')]
    private $price_ht;

    #[ORM\Column(type: 'float')]
    private $tva;

    #[ORM\OneToMany(mappedBy: 'id_product', targetEntity: ProductFacture::class)]
    private $productFactures;

    #[ORM\OneToMany(mappedBy: 'id_product', targetEntity: ProductDevis::class)]
    private $productDevis;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'products')]
    private $userId;

    public function __construct()
    {
        $this->productFactures = new ArrayCollection();
        $this->productDevis = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPriceHt(): ?float
    {
        return $this->price_ht;
    }

    public function setPriceHt(float $price_ht): self
    {
        $this->price_ht = $price_ht;

        return $this;
    }

    public function getTva(): ?float
    {
        return $this->tva;
    }

    public function setTva(float $tva): self
    {
        $this->tva = $tva;

        return $this;
    }

    /**
     * @return Collection<int, ProductFacture>
     */
    public function getProductFactures(): Collection
    {
        return $this->productFactures;
    }

    public function addProductFacture(ProductFacture $productFacture): self
    {
        if (!$this->productFactures->contains($productFacture)) {
            $this->productFactures[] = $productFacture;
            $productFacture->setIdProduct($this);
        }

        return $this;
    }

    public function removeProductFacture(ProductFacture $productFacture): self
    {
        if ($this->productFactures->removeElement($productFacture)) {
            // set the owning side to null (unless already changed)
            if ($productFacture->getIdProduct() === $this) {
                $productFacture->setIdProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ProductDevis>
     */
    public function getProductDevis(): Collection
    {
        return $this->productDevis;
    }

    public function addProductDevi(ProductDevis $productDevi): self
    {
        if (!$this->productDevis->contains($productDevi)) {
            $this->productDevis[] = $productDevi;
            $productDevi->setIdProduct($this);
        }

        return $this;
    }

    public function removeProductDevi(ProductDevis $productDevi): self
    {
        if ($this->productDevis->removeElement($productDevi)) {
            // set the owning side to null (unless already changed)
            if ($productDevi->getIdProduct() === $this) {
                $productDevi->setIdProduct(null);
            }
        }

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->userId;
    }

    public function setUserId(?User $userId): self
    {
        $this->userId = $userId;

        return $this;
    }
}

src/Entity/ProductDevis.php
<?php

namespace App\Entity;

use App\Repository\ProductDevisRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductDevisRepository::class)]
class ProductDevis
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Devis::class, inversedBy: 'productDevis')]
    private $id_devis;

    #[ORM\ManyToOne(targetEntity: Product::class, inversedBy: 'productDevis')]
    private $id_product;

    #[ORM\Column(type: 'integer')]
    private $quantity;

    #[ORM\Column(type: 'float')]
    private $total_ht;

    #[ORM\Column(type: 'float')]
    private $total_ttc;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdDevis(): ?Devis
    {
        return $this->id_devis;
    }

    public function setIdDevis(?Devis $id_devis): self
    {
        $this->id_devis = $id_devis;

        return $this;
    }

    public function getIdProduct(): ?Product
    {
        return $this->id_product;
    }

    public function setIdProduct(?Product $id_product): self
    {
        $this->id_product = $id_product;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getTotalHt(): ?float
    {
        return $this->total_ht;
    }

    public function setTotalHt(float $total_ht): self
    {
        $this->total_ht = $total_ht;

        return $this;
    }

    public function getTotalTtc(): ?float
    {
        return $this->total_ttc;
    }

    public function setTotalTtc(float $total_ttc): self
    {
        $this->total_ttc = $total_ttc;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $adresse;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ville;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $code_postal;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $telephone;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $portable;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $fax;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $website;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $raison_sociale;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $forme_juridique;

    #[ORM\OneToMany(mappedBy: 'id_user', targetEntity: Facture::class)]
    private $id_customer;

    #[ORM\OneToMany(mappedBy: 'id_user', targetEntity: Devis::class)]
    private $devis;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Customer::class)]
    private $customers;

    #[ORM\OneToMany(mappedBy: 'userId', targetEntity: Product::class)]
    private $products;

    public function __construct()
    {
        $this->id_customer = new ArrayCollection();
        $this->devis = new ArrayCollection();
        $this->customers = new ArrayCollection();
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(?int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getPortable(): ?string
    {
        return $this->portable;
    }

    public function setPortable(?string $portable): self
    {
        $this->portable = $portable;

        return $this;
    }

    public function getFax(): ?string
    {
        return $this->fax;
    }

    public function setFax(?string $fax): self
    {
        $this->fax = $fax;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raison_sociale;
    }

    public function setRaisonSociale(?string $raison_sociale): self
    {
        $this->raison_sociale = $raison_sociale;

        return $this;
    }

    public function getFormeJuridique(): ?string
    {
        return $this->forme_juridique;
    }

    public function setFormeJuridique(?string $forme_juridique): self
    {
        $this->forme_juridique = $forme_juridique;

        return $this;
    }

    /**
     * @return Collection<int, Facture>
     */
    public function getIdCustomer(): Collection
    {
        return $this->id_customer;
    }

    public function addIdCustomer(Facture $idCustomer): self
    {
        if (!$this->id_customer->contains($idCustomer)) {
            $this->id_customer[] = $idCustomer;
            $idCustomer->setIdUser($this);
        }

        return $this;
    }

    public function removeIdCustomer(Facture $idCustomer): self
    {
        if ($this->id_customer->removeElement($idCustomer)) {
            // set the owning side to null (unless already changed)
            if ($idCustomer->getIdUser() === $this) {
                $idCustomer->setIdUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Devis>
     */
    public function getDevis(): Collection
    {
        return $this->devis;
    }

    public function addDevi(Devis $devi): self
    {
        if (!$this->devis->contains($devi)) {
            $this->devis[] = $devi;
            $devi->setIdUser($this);
        }

        return $this;
    }

    public function removeDevi(Devis $devi): self
    {
        if ($this->devis->removeElement($devi)) {
            // set the owning side to null (unless already changed)
            if ($devi->getIdUser() === $this) {
                $devi->setIdUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Customer>
     */
    public function getCustomers(): Collection
    {
        return $this->customers;
    }

    public function addCustomer(Customer $customer): self
    {
        if (!$this->customers->contains($customer)) {
            $this->customers[] = $customer;
            $customer->setUser($this);
        }

        return $this;
    }

    public function removeCustomer(Customer $customer): self
    {
        if ($this->customers->removeElement($customer)) {
            // set the owning side to null (unless already changed)
            if ($customer->getUser() === $this) {
                $customer->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setUserId($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getUserId() === $this) {
                $product->setUserId(null);
            }
        }

        return $this;
    }
}

templates/facture/facture.html.twig
{% extends 'base.html.twig' %}

{% block title %}Facture{% endblock %}

{% block body %}
    

<section class="flex-facture">
    <div class="block-user1">
        <hr> 
        <p>
            {{ app.user.raisonSociale }} <br>
            {{ app.user.adresse }} <br>
            {{ app.user.codePostal }} {{ app.user.ville }}
        </p>
        <p>
            Tel: {{ app.user.telephone }} / Por: {{ app.user.portable }}
        </p>
        <p> Email: {{ app.user.email }}</p>
        <hr>
    </div>
    <div class="block-user2">
        <h2>FACTURE # {{ facture.codeFacture }}</h2>
        <p>
            <strong>{{ facture.idCustomer.lastName }} {{ facture.idCustomer.firstName }}</strong> <br>
            {{ facture.idCustomer.codePostal }} {{ facture.idCustomer.ville }}
        </p>
        <p>
            Tel: {{ facture.idCustomer.telephone }} <br>
            Por: {{ facture.idCustomer.portable }}
        </p>
        <p>Email: {{ facture.idCustomer.mail }}</p>
    </div>    
</section>

<section class="flex-facture">
    <div class="block-product">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Description</th>
                    <th scope="col">Prix HT</th>
                    <th scope="col">TVA</th>
                    <th scope="col">Qté</th>
                    <th scope="col">Total TTC</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
            {% set total = 0 %}
            {% set totalHt = 0 %}
            {% set totalTva = 0 %}
            {% set totalProduct = 0 %}
            {% set totalProductHt = 0 %}
            {% set totalProductTva = 0 %}
            {% for product in facture.productFactures %}
                <tr>
                    <td>{{ product.idProduct.description |saut_de_ligne |raw }}</td>
                    <td>{{ product.idProduct.priceHt }}</td>
                    <td>{{ product.idProduct.tva }}</td>
                    <td>{{ product.quantity }}</td>
                    <td>
                        {% set totalProduct = (product.idProduct.priceHt + (product.idProduct.priceHt * (product.idProduct.tva / 100))) * product.quantity %}
                        {% set totalProductHt = product.quantity * product.idProduct.priceHt %}
                        {% set totalProductTva = product.quantity * (product.idProduct.priceHt * (product.idProduct.tva / 100)) %}
                        {{ totalProduct |round_decimal }}
                        {% set total = total + totalProduct %}
                        {% set totalHt = totalHt + totalProductHt %}
                        {% set totalTva = totalTva + totalProductTva %}
                    </td>
                    <td><a href="{{ path('del_facture_product', {'id': product.id}) }}" onclick="return confirm('Supprimer le produit?')"><i class="fa-solid fa-trash"></i></a></td>
                    <td><a href="#" data-bs-toggle="modal" data-bs-target="#exampleModal{{ product.id }}" data-bs-whatever="@getbootstrap"><i class="fa-solid fa-pen-to-square"></i></a></td>
                </tr> 

{# ### #}
{# modal Bootstrap #}
<div class="modal fade" id="exampleModal{{ product.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modifier le produit #{{ product.id }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{ path('update_facture_product', {"id": product.id, "idProduct": product.idProduct.id}) }}" method="post">          
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Description:</label>
            <textarea class="form-control" id="message-text" rows="5" name="message-name">{{ product.idProduct.description }}</textarea>
          </div>
          <div class="mb-3">
            <label for="price-name" class="col-form-label">Prix HT:</label>
            <input type="number" class="form-control" id="price-name" name="price-name" value="{{ product.idProduct.priceHt }}" min="0" step="0.01">
          </div>
          <div class="mb-3">
            <label for="quantity-name" class="col-form-label">Quantité:</label>
            <input type="number" class="form-control" id="quantity-name" name="quantity-name" value="{{ product.quantity }}" min="1">
          </div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Fermer</button>
        <button type="submit" class="btn btn-danger">Mettre à jour</button>
      </div>
      </form>
    </div>
  </div>
</div>
{# end modal #}


            {% endfor %}     
            </tbody>
        </table>
        <div class="btn-product">
            <div class="button_slide slide_right">
                <a href="#" data-bs-toggle="modal" data-bs-target="#newProduct"><i class="fa-solid fa-plus"></i> &nbsp;Ajouter </a>
            </div>
        </div>
    </div>    
</section>

<section class="flex-facture">
    <div class="block-product">
        <br>
        <dl>
          <dt>{{ total |round_decimal }}</dt>
          <dd>TOTAL TTC</dd>
          <dt>{{ totalTva |round_decimal }}</dt>
          <dd>TVA</dd>
          <dt>{{ totalHt |round_decimal }}</dt>
          <dd>Total HT</dd>
          <dt></dt>
          <dd></dd>
          <dt>{{ facture.modePaiement }}</dt>
          <dd>Mode de paiement</dd>
        </dl>
    </div>    
</section>

{# modal new product #}
<div class="modal fade" id="newProduct" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ajouter un produit/service</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{ path('new_facture_product', {"id": facture.id}) }}" method="post">
          <div class="mb-3">
            <label for="ref-name" class="col-form-label">Référence:</label>
            <input type="text" class="form-control" id="ref-name" name="ref-name">
          </div>
          <div class="mb-3">
            <label for="description-text" class="col-form-label">Description:</label>
            <textarea class="form-control" id="description-text" rows="5" name="description-name"></textarea>
          </div>
          <div class="mb-3">
            <label for="price-name" class="col-form-label">Prix HT:</label>
            <input type="number" class="form-control" id="price-name" name="price-name" min="0" step="0.01">
          </div>
          <div class="mb-3">
            <label for="quantity-name" class="col-form-label">Quantité:</label>
            <input type="number" class="form-control" id="quantity-name" name="quantity-name" min="1">
          </div>
          <div class="mb-3">
            <label for="tva-name" class="col-form-label">TVA:</label>
            <select class="form-select" aria-label="Default select example" id="quantity-name" name="tva-name">                
                <option value="20">20%</option>
                <option value="10">10%</option>
                <option value="5">5%</option>
            </select>            
          </div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Fermer</button>
        <button type="submit" class="btn btn-success">Ajouter</button>
      </div>
      </form>
    </div>
  </div>
</div>
{# fin modal #}
{% endblock %}

templates/facture/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des factures{% endblock %}

{% block body %}
<hr>
<table class="titleTab">
  <tr>
    <td class='left'>
        <h1 class="userTitle"><i class="fa-solid fa-users"></i> &nbsp;&nbsp; Liste des Factures</h1>
    </td>
    <td class='right'>        
        <div class="button_slide slide_right"><a href="{{ path('app_customer_new') }}"><i class="fa-solid fa-plus"></i> &nbsp;Ajouter </a></div>
    </td>
  </tr>
</table>    
<hr>

<div class="dataList">
    <div class="table-responsive">
        <table class="table table-striped table-dark">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Date</th>
              <th scope="col">Client</th>
              <th scope="col">Mode de Paiement</th>
              {# <th scope="col">Code Postal</th>
              <th scope="col">Ville</th>
              <th scope="col">Téléphone</th>
              <th scope="col">Portable</th> #}
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
          {% for facture in facturesByPage %}
            <tr>
                <td>{{ facture.codeFacture }}</td>
                <td>{{ facture.date|date("d-m-Y") }}</td>
                <td>{{ facture.idCustomer.lastName }} {{ facture.idCustomer.firstName }}</td>
                <td>{{ facture.modePaiement }}</td>
                {# <td>{{ customer.codePostal }}</td>
                <td>{{ customer.ville }}</td>                
                <td>{{ customer.telephone }}</td>
                <td>{{ customer.portable }}</td> #}
                <td><a href="{{ path('app_facture_id', {'id': facture.id}) }}"><i class="fa-solid fa-magnifying-glass"></i></a></td>
                <td><a href="{{ path('app_facture_id', {'id': facture.id}) }}"><i class="fa-solid fa-pen-to-square"></i></a></td>
            </tr>
          {% else %}
            <tr>
                <td colspan="14">aucun résultat</td>
            </tr>
          {% endfor %}      
          </tbody>
        </table>
        <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        {{ knp_pagination_render(facturesByPage) }}
        </ul>
        </nav>
    </div>
</div>

{% endblock %}